### ISSUE TITLE
Prepoznavanje nota u notnoj svesci i generisanje melodije na osnovu nota

### ISSUE THREAD

**Issue by visnja** [ftn-ai-lab/ori-2017-siit#16]
@ivan7792 
Milica Mlađenović sw23-2014 Grupa 1

**Opis problema:**
Sa date slike notne sveske potrebno je izdvojiti note i znakove (pauze, povisilice, snizilice, rezrešilice) i odrediti tip odnosno dužinu trajanja i na osnovu detektovanog niza izgenerisati melodiju.

**Algoritmi za prepoznavanje znakova sa slike:**

- Neural  Network
- Convolution Neural Network

**Podaci koji se koriste:**

- Pravljenje sopstvenih skupova podataka (datasets) za treniranje i testiranje.

**Metrike za poredjenje ispravnosti resenja:**

- procenat uspešnosti predikcije vrste simbola sa slike na osnovu ručno pripremljenih labeliranih podataka (slika simbola).
- procenat uspešnosti predikcije tona note sa slike na osnovu ručno pripremljenih labeliranih podataka

**Validacija rešenja:**
Validacija rešenja se obavlja pomoću testnog skupa slika. U zavisnosti od broja tačno detektovanih simbola, prikazuje se koeficijent uspešnosti algoritma u intervalu [0, 100].

**Comment by ivan7792** [comment]
Primetim da je prijava iskopirana od kolege Vladimira. Par stvari značajno razlikuje vaše dve teme, pa ih je potrebno detaljnije opisati:
      - Da li prepoznajete rukom pisane note ili štampane? I kod jednih i kod drugih postoji veliki broj različitih zapisa, gde se više nota spaja u jednu i sl. Da li prepoznajete i takve slučajeve ili ne?
      - Na koji način planirate da prepoznajete notni sistem, pošto je bitno gde se koja nota nalazi na skali?
Ispravke je potrebno dodati u naredna 24h.
