### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by saraperic13** [ftn-ai-lab/ori-2017-siit#17]
**Članovi tima:**
Sara Perić (sw26-2014)
Grupa 2
Asistent: Ivan Perić

**Opis problema:**
Na osnovu unete poruke detektuje se sentiment i korisnik dobija odgovor (koji predstavlja neku zanimljivu činjenicu) suprotnog sentimenta pri čemu prioritet imaju oni odgovori koji sadrže neku od ključnih reči iz poruke.

**Algoritmi:**
Uneta poruka će se prvobitno obraditi tako da se izignorišu znakovi interpunkcije kao i beznačajne reči (poput veznika).
Koristiće se bag of words ili n-gram model za ulazni vektor.
Za klasifikaciju NB classifier.

**Metrika za proveru ispravnosti rešenja:**
Procenat odgovora koji odgovaraju suprotnom sentimentu i imaju veze sa upućenom porukom.

**Podaci koji se koriste:**
Trening i testni podaci: https://www.crowdflower.com/wp-content/uploads/2016/07/text_emotion.csv
Kao odgovori: ručno kreiran dataset.

**Validacija rešenja:**
70% testnih podataka koristiće se za treniranje, ostalih 30% za testiranje.

**Comment by ivan7792** [comment]
Na koji način vršite izbor "zanimljive činjenice" suprotnog senitmenta? Prvi deo se poklapa sa gradivom koje je rađeno na vežbama, pa onda drugi deo predstavlja fokus projekta. Da li zanimljivu činjenicu određujete nekom vrstom predikcije, ili vršite obično brojanje poklapanja reči sa svim primerima suprotnog sentimenta?

**Comment by saraperic13** [comment]
Hvala na odgovoru. Odustajem od projekta.
